universal_binaries:
- replace: true
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  - freebsd
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: freebsd
    goarch: arm64
  - goos: windows
    goarch: arm64
  flags:
  - -trimpath
  binary: kced
  ldflags:
  - -s -w -X github.com/kong/go-apiops/cmd.VERSION={{ .Tag }} -X github.com/kong/go-apiops/cmd.COMMIT={{ .ShortCommit }}
snapshot:
  name_template: "{{ .Tag }}"
