# Metadata fields start with an underscore (_)
# Fields that do not start with an underscore represent Kong entities and attributes

_comment: this is file1

# _format_version is mandatory,
# it specifies the minimum version of Kong that supports the format
_format_version: "3.0"

# _transform is optional, defaulting to true.
# It specifies whether schema transformations should be applied when importing this file
# as a rule of thumb, leave this setting to true if you are importing credentials
# with plain passwords, which need to be encrypted/hashed before storing on the database.
# On the other hand, if you are reimporting a database with passwords already encrypted/hashed,
# set it to false.
_transform: true

services:
- name: file1-service-1
  url: http://example.com
  routes:
  - name: my_route
    paths:
    - /path
- name: file1-service-2
  url: https://example.org

routes:
- name: file1-route-1
  hosts: ["hello.com"]
