# if the servers block has no hostname, then the default 'localhost'
# should be injected.
# OAS default for the url is "/" but that is useless for Kong, since there
# would be no host. Using 'localhost' is just slightly less useless :/
#
# scheme default: https
# hostname default: localhost
# port default: based on scheme

openapi: '3.0.0'
info:
  title: Simple API overview
  version: v2
servers:
  - url: /
paths:
  /:
    get:
      operationId: OpsId
      summary: List API versions
      responses:
        '200':
          description: |-
            200 response
