# The path parameters should be converted to a regex for matching the route.
# Including creating captures of the parameter values.

openapi: 3.0.3
info:
  title: Path parameter test
  version: v1
servers:
  - url: "https://example.com"

paths:
  # simple regex capture names. Also the path has a trailing slash.
  /demo/{something}/else/{todo}/:
    get:
      operationId: opsid
      parameters:
        - in: path
          name: something
          required: true
          schema:
            type: string
        - in: path
          name: todo
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  # note that the names are not valid regex capture names, hence they must be sanitized
  # in the output. Also the path has NO trailing slash.
  /demo/{ white space }/{x*()_-+=x}/{-To_Do}:
    get:
      operationId: opsid
      parameters:
        - in: path
          name: " white space "
          required: true
          schema:
            type: string
        - in: path
          name: "x*()_-+=x"
          required: true
          schema:
            type: string
        - in: path
          name: -To_Do
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  # some more complex paths, with and without parameters
  # examples from: https://github.com/Kong/insomnia/pull/5246
  /batchs(Material='iron',Batch='10'):
    get:
      responses:
        "200":
          description: no parameters
      operationId: getBatchNoParams
  /batchs(Material='{Material}',Batch='{Batch}'):
    get:
      parameters:
        - in: path
          name: Material
          required: true
          schema:
            type: string
        - in: path
          name: Batch
          required: true
          schema:
            type: string
      responses:
        "200":
          description: An echo message.
      operationId: getBatchWithParams
    post:
      # test validating not escaping the path twice; we have 2 methods on 1 path
      parameters:
        - in: path
          name: Material
          required: true
          schema:
            type: string
        - in: path
          name: Batch
          required: true
          schema:
            type: string
      responses:
        "200":
          description: An echo message.
      operationId: postBatchWithParams
  # dollar sign in path
  /some/$test:
    get:
      responses:
        "200":
          description: no parameters
      operationId: dollar-sign
