# openapi2kong.go should not create an extra service
# when there are no top-level doc servers defined.

openapi: 3.0.0
info:
  title: Multi-Service API
  version: 1.0.0

paths:
  /users:
    get:
      servers:
        - url: https://user-service.example.com
      responses:
        '200':

  /orders:
    post:
      servers:
        - url: https://order-service.example.com
      responses:
        '201':