openapi: 3.0.0

info:
  description: Test service
  version: 1.0.0
  title: Test Service

x-kong-plugin-request-validator:
  enabled: true

paths:
  /sample-group/sample-service/sample-api/v1/get-result:
    get:
      summary: Get Results
      description: Get Results.
      responses:
        "200":
          description: The request has succeeded.
    options:
      responses:
        "200":
          description: Generic OPTIONS response

  /sample-group/sample-service/sample-api/v2/get-result:
    get:
      summary: Get Results
      description: Get Results.
      responses:
        "200":
          description: The request has succeeded.
    options:
      responses:
        "200":
          description: Generic OPTIONS response
