openapi: 3.0.3
info:
  version: v1
  title: Example API
paths:
  /api/v1/example:
    post:
      operationId: exampleOperation
      x-kong-plugin-rate-limiting-advanced:
        enabled: true
        config:
          limit: [500]
      parameters:
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            enum:
              - application/xml
              - text/xml
